#!/usr/bin/env python3
"""
Decode all test images generated by AztecDecodeValidationTests.

Usage:
    1. Run Swift test to generate images:
       swift test --filter generate_all_test_images

    2. Run this script to decode all images:
       source ~/.venv/zxing/bin/activate  # or /tmp/zxing-venv/bin/activate
       python3 Scripts/decode_all_tests.py
"""

import sys
from pathlib import Path

def main():
    try:
        import zxingcpp
        from PIL import Image
    except ImportError as e:
        print(f"Error: Required package not installed: {e}")
        print("Run: pip install zxing-cpp pillow")
        return 1

    manifest_path = Path("/tmp/aztec_test_manifest.txt")
    if not manifest_path.exists():
        print("Error: Manifest file not found!")
        print("Run Swift test first: swift test --filter generate_all_test_images")
        return 1

    print("=" * 70)
    print("AZTECLIB DECODE VALIDATION RESULTS")
    print("=" * 70)
    print()

    passed = 0
    failed = 0
    errors = []

    with open(manifest_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split("|")
            if len(parts) != 4:
                continue

            name, payload, path, info = parts

            # Unescape payload
            payload = payload.replace("\\n", "\n").replace("\\t", "\t").replace("\\|", "|").replace("\\\\", "\\")

            # Check if image exists
            if not Path(path).exists():
                print(f"SKIP {name}: Image not found at {path}")
                continue

            # Decode
            try:
                img = Image.open(path).convert("RGB")
                barcodes = zxingcpp.read_barcodes(img)

                aztec_results = [b for b in barcodes if b.format == zxingcpp.BarcodeFormat.Aztec]

                if not aztec_results:
                    print(f"FAIL {name}: No Aztec barcode detected")
                    print(f"     Payload: {repr(payload)[:50]}")
                    print(f"     Symbol: {info}")
                    failed += 1
                    errors.append({
                        "name": name,
                        "payload": payload,
                        "info": info,
                        "error": "No Aztec barcode detected"
                    })
                    continue

                decoded = aztec_results[0].text

                if decoded == payload:
                    print(f"PASS {name}: {info}")
                    passed += 1
                else:
                    print(f"FAIL {name}: Content mismatch")
                    print(f"     Expected: {repr(payload)[:50]}")
                    print(f"     Decoded:  {repr(decoded)[:50]}")
                    print(f"     Symbol: {info}")
                    failed += 1
                    errors.append({
                        "name": name,
                        "payload": payload,
                        "decoded": decoded,
                        "info": info,
                        "error": "Content mismatch"
                    })

            except Exception as e:
                print(f"ERROR {name}: {e}")
                failed += 1
                errors.append({
                    "name": name,
                    "payload": payload,
                    "info": info,
                    "error": str(e)
                })

    print()
    print("=" * 70)
    print("SUMMARY")
    print("=" * 70)
    print(f"Passed: {passed}")
    print(f"Failed: {failed}")
    print(f"Total:  {passed + failed}")

    if passed + failed > 0:
        print(f"Success rate: {100 * passed / (passed + failed):.1f}%")

    if errors:
        print()
        print("Failed tests details:")
        for err in errors:
            print(f"  - {err['name']}: {err['error']}")
            print(f"    Symbol: {err.get('info', 'N/A')}")
            if 'decoded' in err:
                print(f"    Expected: {repr(err['payload'])[:40]}")
                print(f"    Got:      {repr(err['decoded'])[:40]}")

    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
